### ISSUE TITLE
Index page is blank

### ISSUE THREAD

**Issue by pirateutopia** [ekch2h2/h2-app#17]
https://h2-app.web.app/ is blank and no content.

**Comment by pirateutopia** [comment]
![error](https://user-images.githubusercontent.com/5465216/95541401-25e74000-09a8-11eb-8f3c-ae33425796c4.jpg)

**Comment by lishenxydlgzs** [comment]
Probably related to this issues: https://stackoverflow.com/questions/53514758/redux-typeerror-cannot-read-property-apply-of-undefined

**Comment by lishenxydlgzs** [comment]
Made a change to exclude "Windows" and "Android" from the redux dev tools, release a new version of https://h2-app.web.app/

**Comment by pirateutopia** [comment]
Great!

lishenxydlgzs <notifications@github.com> 于2020年10月8日周四 下午9:53写道：
